services:
  - type: web
    name: arabians-shopping-zone
    runtime: node
    plan: free
    region: singapore
    buildCommand: npm run build || true
    startCommand: node server/index.js
    healthCheckPath: /api/health
    autoDeploy: true
    domains:
      - arabiansshoppingzone.shop
      - www.arabiansshoppingzone.shop
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DEV_SECRET
        value: hamza786
      - key: MONGODB_URI
        value: mongodb+srv://mohammadhamza2518_db_user:H6t7ji6iIQOoO4ME@cluster0.xfjp4y5.mongodb.net/arabians_shopping_zone?retryWrites=true&w=majority&appName=Cluster0
      - key: RAZORPAY_KEY_ID
        value: rzp_live_TaICrfbpvjAX2q
      - key: RAZORPAY_KEY_SECRET
        value: OP3A8g7vKiYzHmtNRJpqWDlv
