import json
import os

products = [
    # 1. HEALTH PRODUCTS (SUNNAH FOODS)
    {
        "id": "talbina-vanilla",
        "name": "Arabian's Talbeena Nutritional Breakfast (Vanilla Dry Fruits)",
        "category": "health",
        "price": 349,
        "mrp": 449,
        "rating": 4.9,
        "reviewsCount": 148,
        "netWeight": "250 Gram",
        "badge": "Flagship Brand",
        "stock": 50,
        "image": "/assets/talbina/talbina_vanilla_dryfruits.png",
        "gallery": ["/assets/talbina/talbina_vanilla_dryfruits.png"],
        "description": "Original Arabian's Talbina crafted from whole sprouted barley (Jau), premium California almonds, green pistachios, cashews and natural vanilla. Prepared in just 5 minutes with warm milk or water.",
        "benefits": ["Sunnah superfood recommended for soothing heart and grief", "High dietary fiber that heals digestion, acidity and gut health", "Natural stamina booster without artificial chemicals", "Ready in 5 minutes — wholesome family breakfast"],
        "tags": ["Sunnah Food", "100% Veg", "Ready in 5 Min", "High Fiber"]
    },
    {
        "id": "talbina-milk-mawa",
        "name": "Arabian's Talbeena Nutritional Breakfast (Milk Mawa Flavour)",
        "category": "health",
        "price": 349,
        "mrp": 449,
        "rating": 4.8,
        "reviewsCount": 96,
        "netWeight": "250 Gram",
        "badge": "Customer Favorite",
        "stock": 45,
        "image": "/assets/talbina/talbina_milk_mawa.png",
        "gallery": ["/assets/talbina/talbina_milk_mawa.png"],
        "description": "Rich, creamy traditional Milk Mawa infused Talbina packed with crunchy dry fruits. Combines the heritage taste of authentic mawa dessert with the supreme nutritional healing of sunnah barley.",
        "benefits": ["Rich in calcium and healthy fats for joint strength", "Delicious creamy taste loved by elders and youth alike", "Zero refined sugar; naturally sweetened with dried dates and nuts", "Instant energy replenishment"],
        "tags": ["Milk Mawa", "Energy Booster", "Sunnah Recipe"]
    },
    {
        "id": "talbina-chocolate",
        "name": "Arabian's Talbeena For Kids (Chocolate Flavour - 1+ Years)",
        "category": "health",
        "price": 369,
        "mrp": 499,
        "rating": 4.9,
        "reviewsCount": 112,
        "netWeight": "250 Gram",
        "badge": "Kids Special",
        "stock": 40,
        "image": "/assets/talbina/talbina_chocolate_kids.png",
        "gallery": ["/assets/talbina/talbina_chocolate_kids.png"],
        "description": "Specially formulated for toddlers and growing children aged 1 year plus. Made with natural Dutch cocoa, stone-ground barley, micronutrients and pulverized dry fruits for sharp memory and immunity.",
        "benefits": ["Yummy chocolate taste that kids drink without fuss", "Promotes brain development and bone density in growing children", "Free from preservatives, artificial colors or excess sucrose"],
        "tags": ["Kids 1+ Years", "Brain Nutrition", "Chocolate"]
    },
    {
        "id": "talbina-baby-barley",
        "name": "Arabian's Talbeena Baby Cereal With Barley (3+ Years)",
        "category": "health",
        "price": 329,
        "mrp": 429,
        "rating": 4.8,
        "reviewsCount": 84,
        "netWeight": "200 Gram",
        "badge": "Gentle Formula",
        "stock": 35,
        "image": "/assets/talbina/talbina_baby_barley.png",
        "gallery": ["/assets/talbina/talbina_baby_barley.png"],
        "description": "Ultra-fine, gentle barley cereal designed for delicate stomachs. Fortified with essential vitamins, iron, and fiber to support digestion and steady growth.",
        "benefits": ["Easy to swallow and gentle on little tummies", "Prevents constipation and indigestion naturally", "100% natural, lab-tested hygienic Sunnah cereal"],
        "tags": ["Baby Cereal", "3+ Years", "Easy Digestion"]
    },
    {
        "id": "talbina-dry-dates",
        "name": "Arabian's Talbeena With Dry Dates & Vanilla Flavour",
        "category": "health",
        "price": 379,
        "mrp": 499,
        "rating": 5.0,
        "reviewsCount": 167,
        "netWeight": "250 Gram",
        "badge": "Royal Sidr Blend",
        "stock": 60,
        "image": "/assets/talbina/talbina_dry_dates_vanilla.png",
        "gallery": ["/assets/talbina/talbina_dry_dates_vanilla.png"],
        "description": "The ultimate Sunnah pairing of Ajwa & Medjool dried dates with roasted barley and aromatic vanilla. Rich in iron, natural fructose, and antioxidants for peak vitality.",
        "benefits": ["Infused with nutrient-dense dates for natural sweetness and hemoglobin", "Sustained energy release without sugar crash", "Supports cardiovascular and nervous system wellness"],
        "tags": ["Dry Dates", "Natural Iron", "Ajwa Blend"]
    },
    {
        "id": "honey-mix-dryfruits",
        "name": "Arabians Royal Sidr Honey Mix with Dry Fruits",
        "category": "health",
        "price": 699,
        "mrp": 899,
        "rating": 4.9,
        "reviewsCount": 78,
        "netWeight": "450 Gram Hexagonal Jar",
        "badge": "Immunity Powerhouse",
        "stock": 30,
        "image": "/assets/studio/honey_mix_dryfruits.jpg",
        "gallery": ["/assets/studio/honey_mix_dryfruits.jpg"],
        "description": "100% Raw unprocessed Sidr Honey packed with roasted California almonds, Iranian pistachios, cashews, and whole dried figs. A royal morning vitality spoon.",
        "benefits": ["Boosts vigor, immunity, and daily stamina", "Natural cold, cough, and throat relief", "Pure Sunnah recipe with raw unheated Sidr honey"],
        "tags": ["Pure Honey", "Dry Fruits Mix", "Sunnah Health"]
    },
    {
        "id": "real-pure-honey",
        "name": "Arabians 100% Pure Raw Sidr Honey",
        "category": "health",
        "price": 549,
        "mrp": 749,
        "rating": 4.9,
        "reviewsCount": 65,
        "netWeight": "500 Gram",
        "badge": "100% Pure Raw",
        "stock": 40,
        "image": "/assets/studio/honey_mix_dryfruits.jpg",
        "gallery": ["/assets/studio/honey_mix_dryfruits.jpg"],
        "description": "Pure single-origin wild Sidr berry nectar honey. Unpasteurized, unheated, and unfiltered to preserve all natural bee pollen, enzymes, and medicinal nutrients.",
        "benefits": ["Natural antibiotic and wound healing properties", "Immediate soothing for digestive and respiratory health", "Zero sugar or corn syrup dilution"],
        "tags": ["Raw Sidr Honey", "Unfiltered", "Medicinal Grade"]
    },

    # 2. WEARING PRODUCTS (MEN'S ROYAL ATTIRE ONLY)
    {
        "id": "thobe-saudi-classic-white",
        "name": "Luxury Saudi Cut Pure White Arabian Thobe",
        "category": "wearing",
        "price": 1699,
        "mrp": 2299,
        "rating": 5.0,
        "reviewsCount": 130,
        "sizes": ["52 (S)", "54 (M)", "56 (L)", "58 (XL)", "60 (XXL)"],
        "badge": "Saudi Classic",
        "stock": 40,
        "image": "/assets/studio/mens_white_thobe.jpg",
        "gallery": ["/assets/studio/mens_white_thobe.jpg"],
        "description": "Crisp, pristine Saudi style straight-cut white jubba tailored with stiff standing collar, concealed snap placket, and deep dual pockets. Engineered for Jummah prayers, Umrah, and everyday Islamic nobility.",
        "benefits": ["Non-see-through high-density poly-viscose cloth", "Stain-resistant and wrinkle-resistant easy iron finish", "Tailored to authentic Riyadh proportions"],
        "tags": ["Saudi White", "Umrah Ready", "Men's Jubba"]
    },
    {
        "id": "thobe-al-noor-signature",
        "name": "Al-Noor Signature Embroidered Designer Thobe",
        "category": "wearing",
        "price": 1899,
        "mrp": 2699,
        "rating": 4.9,
        "reviewsCount": 89,
        "sizes": ["52 (S)", "54 (M)", "56 (L)", "58 (XL)", "60 (XXL)"],
        "badge": "Al Noor Catalog",
        "stock": 25,
        "image": "/assets/thobes/thobes__al_noor_design_p1_1.png",
        "gallery": ["/assets/thobes/thobes__al_noor_design_p1_1.png", "/assets/studio/mens_white_thobe.jpg"],
        "description": "Handcrafted Al-Noor designer thobe featuring intricate geometric thread embroidery along the collar, placket, and cuffs. Made from luxury Korean drape fabric.",
        "benefits": ["Breathable all-weather fabric for Indian climate", "Discreet phone pocket and miswak slot", "Concealed snap-button finish"],
        "tags": ["Al Noor", "Embroidered", "Wrinkle Free", "Men's Thobe"]
    },
    {
        "id": "thobe-burberry-collar",
        "name": "Arabian Burberry Pattern Collar Luxury Thobe",
        "category": "wearing",
        "price": 1999,
        "mrp": 2799,
        "rating": 4.9,
        "reviewsCount": 64,
        "sizes": ["52 (S)", "54 (M)", "56 (L)", "58 (XL)", "60 (XXL)"],
        "badge": "Trending Style",
        "stock": 20,
        "image": "/assets/thobes/thobes_burberry_design_p1_1.png",
        "gallery": ["/assets/thobes/thobes_burberry_design_p1_1.png"],
        "description": "Sophisticated modern Arabian thobe tailored with designer checked Burberry-inspired accents along the collar stand and placket lining.",
        "benefits": ["Contrast collar styling for festive occasions", "Structured formal collar that retains crisp shape", "Silky soft touch with zero skin irritation"],
        "tags": ["Burberry Trim", "Modern Cut", "Men's Attire"]
    },
    {
        "id": "amama-shareef-madani",
        "name": "Traditional Kashmiri Amama Shareef (7 Meters)",
        "category": "wearing",
        "price": 599,
        "mrp": 899,
        "rating": 4.9,
        "reviewsCount": 72,
        "sizes": ["7 Meters Length"],
        "badge": "Sunnah Crown",
        "stock": 35,
        "image": "/assets/thobes/thobes_al_noor_2_p5_1.png",
        "gallery": ["/assets/thobes/thobes_al_noor_2_p5_1.png"],
        "description": "Pure unadulterated fine cotton Amama Shareef cloth. Available in traditional Sunnah colors (Pure White, Deep Emerald Green, Jet Black). Soft, lightweight, and holds folds firmly.",
        "benefits": ["Prophetic Sunnah headwear for namaz and dignity", "Keeps head cool and absorbs sweat naturally", "Authentic 7-meter wrapping length"],
        "tags": ["Amama Shareef", "Cotton Turban", "Sunnah"]
    },
    {
        "id": "arabians-rumal-shemagh",
        "name": "Arabians Red & White Shemagh Rumal with Heavy Agal",
        "category": "wearing",
        "price": 699,
        "mrp": 999,
        "rating": 4.8,
        "reviewsCount": 58,
        "sizes": ["55x55 Inch Square"],
        "badge": "Arabian Heritage",
        "stock": 30,
        "image": "/assets/thobes/thobes__al_noor_design_p6_1.png",
        "gallery": ["/assets/thobes/thobes__al_noor_design_p6_1.png"],
        "description": "Authentic woven jacquard Red & White Yashmagh (Keffiyeh) accompanied by a heavy double-ring black braided cord (Agal). Complete Gulf style head attire.",
        "benefits": ["Heavy woven tassels and authentic Arabian jacquard patterns", "Durable agal cord that sits firmly without slipping", "Protection against heat, dust and direct sun"],
        "tags": ["Shemagh", "Rumal", "Agal", "Gulf Wear"]
    },
    {
        "id": "islamic-cap-collection",
        "name": "Handcrafted Turkish Velvet & Omani Embroidered Cap Set",
        "category": "wearing",
        "price": 449,
        "mrp": 699,
        "rating": 4.9,
        "reviewsCount": 94,
        "sizes": ["Sizes: 21, 22, 22.5, 23 Inches"],
        "badge": "Pack of 2",
        "stock": 50,
        "image": "/assets/thobes/thobes_al_noor_2_p8_1.png",
        "gallery": ["/assets/thobes/thobes_al_noor_2_p8_1.png"],
        "description": "Set of 2 luxury prayer caps: 1x Hand-embroidered Omani rigid kufi and 1x Rich velvet Turkish prayer topi with intricate gold threadwork. Breathable inner lining.",
        "benefits": ["Non-slip comfortable fit for daily five-time prayers", "Reinforced sweatband to maintain crisp circular shape", "Available in standard Indian head circumferences"],
        "tags": ["Islamic Cap", "Kufi", "Topi", "Prayer Cap"]
    },
    {
        "id": "royal-arabic-bisht",
        "name": "Royal Arabian Bisht / Qubba (Heavy Gold Zari Border)",
        "category": "wearing",
        "price": 3499,
        "mrp": 4999,
        "rating": 5.0,
        "reviewsCount": 46,
        "sizes": ["Free Size (Length 56-60)"],
        "badge": "Groom Royal",
        "stock": 15,
        "image": "/assets/thobes/thobes__al_noor_design_p8_1.png",
        "gallery": ["/assets/thobes/thobes__al_noor_design_p8_1.png"],
        "description": "Traditional Arab ceremonial cloak worn over the thobe for weddings, Eid, and high honors. Hand-trimmed with heavy real metallic gold thread (Zari) along the collar and front lapels.",
        "benefits": ["Gives an instant majestic Sheikh look for grooms and dignitaries", "Includes authentic matching gold braided tasselled cord", "Lightweight sheer luxury wool-blend drape"],
        "tags": ["Royal Bisht", "Groom Cloak", "Gold Zari"]
    },
    {
        "id": "wedding-dulha-turban",
        "name": "Royal Dulha Groom Wedding Turban (Zari Brocade with Kalgi)",
        "category": "wearing",
        "price": 1899,
        "mrp": 2699,
        "rating": 4.9,
        "reviewsCount": 38,
        "sizes": ["Free Size Padded"],
        "badge": "Dulha Special",
        "stock": 18,
        "image": "/assets/thobes/thobes_al_noor_2_p10_1.png",
        "gallery": ["/assets/thobes/thobes_al_noor_2_p10_1.png"],
        "description": "Exquisite pre-tied royal groom turban fashioned from golden Banarasi brocade fabric, adorned with pearl strings and an antique gold Kalgi brooch with green emerald stone.",
        "benefits": ["Pre-tied structured frame — ready to wear in seconds", "Cushioned inner cotton band prevents headache or tightness", "Majestic royal groom presentation"],
        "tags": ["Wedding Turban", "Dulha Pagdi", "Groom Wear"]
    },

    # 3. FRAGRANCE (ATTAR, OUD & BAKHOOR)
    {
        "id": "dehnul-oud-pure",
        "name": "Aged Royal Dehnul Oud (Cambodian Reserve - 6ml)",
        "category": "fragrance",
        "price": 2499,
        "mrp": 3499,
        "rating": 5.0,
        "reviewsCount": 88,
        "netWeight": "6 ml Crystal Bottle",
        "badge": "100% Pure Oil",
        "stock": 20,
        "image": "/assets/studio/dehnul_oud_pure.jpg",
        "gallery": ["/assets/studio/dehnul_oud_pure.jpg"],
        "description": "Distilled from aged wild agarwood trees from the Koh Kong forests of Cambodia. A deep, smoky, woody, and resinous aroma with balsamic sweet dry-down that lingers on clothes for days.",
        "benefits": ["Zero alcohol, 100% pure steam-distilled agarwood oil", "24-48 hours extreme longevity with majestic projection", "Presented in crystal bottle inside antique velvet gift box"],
        "tags": ["Pure Dehnul Oud", "Cambodian", "Alcohol Free"]
    },
    {
        "id": "white-oudh-attar",
        "name": "Imperial White Oudh Non-Alcoholic Attar (12ml)",
        "category": "fragrance",
        "price": 649,
        "mrp": 899,
        "rating": 4.8,
        "reviewsCount": 176,
        "netWeight": "12 ml",
        "badge": "Top Rated",
        "stock": 50,
        "image": "/assets/studio/dehnul_oud_pure.jpg",
        "gallery": ["/assets/studio/dehnul_oud_pure.jpg"],
        "description": "Crisp, airy, and aristocratic blend of white musk, tender agarwood, ambergris, and Taif rose. Clean and refreshing for daily prayers and professional meetings.",
        "benefits": ["Non-alcoholic Halal roll-on perfume oil", "Gentle on sensitive skin with no synthetic burning", "Signature scent loved across all age groups"],
        "tags": ["White Oudh", "Roll On", "12ml", "Long Lasting"]
    },
    {
        "id": "arabian-bakhoor-burner-combo",
        "name": "Arabian Royal Bakhoor & Electric Brass Mabkhara Set",
        "category": "fragrance",
        "price": 1299,
        "mrp": 1799,
        "rating": 4.9,
        "reviewsCount": 94,
        "badge": "Home Blessing",
        "stock": 25,
        "image": "/assets/studio/bakhoor_mabkhara.jpg",
        "gallery": ["/assets/studio/bakhoor_mabkhara.jpg"],
        "description": "Transform your home into an Arabian palace. Includes 100g of slow-burning fragrant Oud Muattar chips infused with musk and rose water, accompanied by a heavy brass electric smokeless burner.",
        "benefits": ["Purifies home air and eliminates stubborn odors", "Electric burner operates safely without charcoal or open flame", "Creates calm serene atmosphere for Quran recitation and meditation"],
        "tags": ["Bakhoor", "Mabkhara", "Electric Burner", "Oud Muattar"]
    },
    {
        "id": "oud-wood-chips-assamese",
        "name": "Arabians Real Assamese Agarwood Oud Chips (50g)",
        "category": "fragrance",
        "price": 1499,
        "mrp": 2199,
        "rating": 5.0,
        "reviewsCount": 41,
        "netWeight": "50 Grams",
        "badge": "Wild Harvested",
        "stock": 18,
        "image": "/assets/studio/dehnul_oud_pure.jpg",
        "gallery": ["/assets/studio/dehnul_oud_pure.jpg"],
        "description": "Resin-dense wild Agarwood chips hand-carved from Assam, India. Emits a warm, deeply spiritual balsamic incense aroma when heated over charcoal or electric mabkhara.",
        "benefits": ["100% natural tree resin with zero synthetic fragrances", "Slow-burning chips that last over 40+ sessions", "Traditional Arabian greeting hospitality ritual"],
        "tags": ["Agarwood Chips", "Oud Wood", "Natural Incense"]
    },

    # 4. HOME DECOR (ISLAMIC CALLIGRAPHY & SACRED ART)
    {
        "id": "acrylic-ayatul-kursi-tugra",
        "name": "3D Royal Gold Acrylic Ayat-ul-Kursi Tugra Wall Art",
        "category": "decor",
        "price": 2199,
        "mrp": 3299,
        "rating": 5.0,
        "reviewsCount": 114,
        "badge": "Handcrafted 3D",
        "stock": 18,
        "image": "/assets/studio/ayatul_kursi_tugra.jpg",
        "gallery": ["/assets/studio/ayatul_kursi_tugra.jpg"],
        "description": "Exquisite 3D mirror-finish gold acrylic Arabic calligraphy plaque featuring Ayat-ul-Kursi in Ottoman Tugra royal crest style. High-grade shatterproof acrylic on matte black backplate.",
        "benefits": ["Brings divine blessings and royal elegance to living room or office", "Ready to hang with heavy-duty pre-installed brass brackets", "Scratch-resistant mirror gold that never fades or tarnishes"],
        "tags": ["Ayat-ul-Kursi", "3D Gold Acrylic", "Islamic Wall Art"]
    },
    {
        "id": "resin-islamic-wall-clock",
        "name": "Emerald Green Geode & Gold Resin Islamic Wall Clock",
        "category": "decor",
        "price": 2799,
        "mrp": 3999,
        "rating": 4.9,
        "reviewsCount": 63,
        "badge": "Masterpiece",
        "stock": 12,
        "image": "/assets/studio/ayatul_kursi_tugra.jpg",
        "gallery": ["/assets/studio/ayatul_kursi_tugra.jpg"],
        "description": "Hand-poured resin geode clock crafted with real crushed crystals, deep emerald pigments, 24K gold leaf veins, and 3D Arabic numerical markers with silent sweep quartz movement.",
        "benefits": ["100% silent quartz movement (no ticking sound)", "Every single clock is unique hand-made artisanal art", "16-inch diameter statement centerpiece"],
        "tags": ["Resin Clock", "Emerald & Gold", "Silent Quartz"]
    },

    # 5. WEDDING PRODUCTS (NIKAH ESSENTIALS - NO WOMEN'S ITEMS)
    {
        "id": "nikah-nama-booklet-luxury",
        "name": "Luxury Velvet Gold-Foil Nikah Nama Certificate Booklet",
        "category": "wedding",
        "price": 1499,
        "mrp": 2299,
        "rating": 5.0,
        "reviewsCount": 152,
        "badge": "Nikah Bestseller",
        "stock": 35,
        "image": "/assets/studio/nikah_nama_booklet.jpg",
        "gallery": ["/assets/studio/nikah_nama_booklet.jpg"],
        "description": "Make the sacred Nikah memorable for eternity. Handbound in deep emerald green velvet with hot-stamped gold foil calligraphy, custom groom/bride name embossing, and parchment archival certificate paper.",
        "benefits": ["Lifetime keepsake preserving your sacred Sunnah contract", "Includes Nikah signature page, Quranic marital verses, and witness slots", "Comes with magnetic closure velvet presentation box"],
        "tags": ["Nikah Nama", "Velvet Gold", "Marriage Certificate", "Sunnah Nikah"]
    },
    {
        "id": "nikah-luxury-pen-box-set",
        "name": "Royal Crystal & Ostrich Feather Nikah Signing Pen Set",
        "category": "wedding",
        "price": 799,
        "mrp": 1199,
        "rating": 4.9,
        "reviewsCount": 73,
        "badge": "Nikah Essential",
        "stock": 28,
        "image": "/assets/studio/nikah_nama_booklet.jpg",
        "gallery": ["/assets/studio/nikah_nama_booklet.jpg"],
        "description": "Exquisite gold signing pen with crystal embellishments and pure white feather, paired with a matching weighted brass pen stand for the signature ceremony.",
        "benefits": ["Smudge-proof archival ink ensures sharp signatures on parchment", "Photogenic centerpiece for wedding ceremony videography", "Presented in cushioned gift box"],
        "tags": ["Nikah Pen", "Feather Pen", "Signing Pen"]
    },
    {
        "id": "haq-mehar-luxury-box",
        "name": "Royal Velvet & Acrylic Haq Mehar Treasury Box",
        "category": "wedding",
        "price": 1299,
        "mrp": 1899,
        "rating": 4.9,
        "reviewsCount": 61,
        "badge": "Royal Mahr",
        "stock": 22,
        "image": "/assets/studio/nikah_nama_booklet.jpg",
        "gallery": ["/assets/studio/nikah_nama_booklet.jpg"],
        "description": "Handcrafted keepsake treasury box for presenting the sacred Haq Mehar (gold coins, cash, or jewelry) during the Nikah ceremony. Features mirror-gold 'Barakallahu Lakuma' laser engraving on clear crystal acrylic with emerald velvet lining.",
        "benefits": ["Dignified Islamic presentation for the bride's Haq Mehar", "Heavy brass latch and velvet interior cushion", "Preserved as a family heirloom"],
        "tags": ["Haq Mehar Box", "Mahr Treasury", "Nikah Gift"]
    }
]

# Update store.json
store_path = "server/data/store.json"
if os.path.exists(store_path):
    with open(store_path, "r", encoding="utf-8") as f:
        store = json.load(f)
    store["products"] = products
    # Ensure categories do not mention women
    for cat in store.get("categories", []):
        if cat["id"] == "wearing":
            cat["name"] = "Wearing & Royal Attire (Men)"
            cat["subtitle"] = "Saudi & Emirati Thobes, Amama, Rumal, Caps & Bisht"
            cat["image"] = "/assets/studio/mens_white_thobe.jpg"
        elif cat["id"] == "fragrance":
            cat["image"] = "/assets/studio/dehnul_oud_pure.jpg"
        elif cat["id"] == "decor":
            cat["image"] = "/assets/studio/ayatul_kursi_tugra.jpg"
        elif cat["id"] == "wedding":
            cat["image"] = "/assets/studio/nikah_nama_booklet.jpg"
            cat["subtitle"] = "Nikah Nama Booklets, Signing Pens & Haq Mehar Boxes"
    with open(store_path, "w", encoding="utf-8") as f:
        json.dump(store, f, indent=2)
    print("store.json reseeded successfully with 100% clean men's catalog and studio images!")
